version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appbooster
    ports:
      - "5434:5432"

  app:
    build: .
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/appbooster
    depends_on:
      - postgres
